export const Permission = {
  SYSTEM_USER_VERIFY_EMAIL: 'SYSTEM_USER_VERIFY_EMAIL',
  SYSTEM_USER_SEND_VERIFY_OTP: 'SYSTEM_USER_SEND_VERIFY_OTP',
  SYSTEM_USER_READ_OTP_CONFIGURATION: 'SYSTEM_USER_READ_OTP_CONFIGURATION',
  ADMIN_SHUTDOWN_SYSTEM: 'ADMIN_SHUTDOWN_SYSTEM',
};