package com.cyber.authify.model.enums;

public enum ErrorCode {
    UNAUTHORIZED,
    ACCESS_DENIED,
    USER_NOT_FOUND,
    EMAIL_ALREADY_EXISTS,
    EMAIL_ALREADY_VERIFIED,
    VALIDATION_FAILED,
    EXPIRED_OTP,
    INVALID_OTP,
    INVALID_CREDENTIALS,
    INVALID_TOKEN_TYPE,
    INVALID_OR_EXPIRED_TOKEN,
    EMAIL_SEND_FAILED,
    INTERNAL_SERVER_ERROR;
}
